spring:
  data:
    mongodb:
      uri: mongodb+srv://gijin22:qIkwtBVNuVzPHOht@cluster0.uwirm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: kafka
  kafka:
    bootstrap-servers: kafka-1:9092
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        isolation.level: read_committed
    producer:
      acks: all
      transaction-id-prefix: "tx-"  #트랜젝션 설정으로 메세지 손실 방지
jwt:
  secret: "jfsgkhdsjkweoiruwqejkrfbrsdfgdsfagbdf"